# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'food.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 275)
        self.label001 = QtWidgets.QLabel(Dialog)
        self.label001.setGeometry(QtCore.QRect(100, 30, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label001.setFont(font)
        self.label001.setObjectName("label001")
        self.label002 = QtWidgets.QLabel(Dialog)
        self.label002.setGeometry(QtCore.QRect(310, 30, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label002.setFont(font)
        self.label002.setObjectName("label002")
        self.pushButton001 = QtWidgets.QPushButton(Dialog)
        self.pushButton001.setGeometry(QtCore.QRect(80, 170, 90, 30))
        self.pushButton001.setObjectName("pushButton001")
        self.pushButton002 = QtWidgets.QPushButton(Dialog)
        self.pushButton002.setGeometry(QtCore.QRect(290, 170, 90, 30))
        self.pushButton002.setObjectName("pushButton002")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(70, 80, 110, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 80, 110, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(True)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.pushButton001.clicked.connect(Dialog.order)
        self.pushButton001.clicked.connect(Dialog.start)
        self.pushButton002.clicked.connect(Dialog.end)
        self.comboBox.currentIndexChanged['int'].connect(Dialog.select_floor)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label001.setText(_translate("Dialog", "楼层"))
        self.label002.setText(_translate("Dialog", "餐品"))
        self.pushButton001.setText(_translate("Dialog", "吃什么呢"))
        self.pushButton002.setText(_translate("Dialog", "就它了"))
        self.label.setText(_translate("Dialog", "每日纠结一刻"))
