# Generated by Django 3.0.5 on 2020-04-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('proId', models.BigAutoField(primary_key=True, serialize=False)),
                ('proName', models.CharField(max_length=200)),
                ('proPrice', models.FloatField(default=0.0)),
                ('proImg', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'productsTable',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=50, unique=True)),
                ('userPass', models.CharField(max_length=50)),
                ('userBirth', models.DateField(null=True)),
                ('userSex', models.CharField(max_length=4)),
                ('pros', models.ManyToManyField(to='userApp.Products')),
            ],
            options={
                'db_table': 'userInfoTable',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('orderMon', models.FloatField()),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserInfo')),
            ],
            options={
                'db_table': 'orderTable',
            },
        ),
    ]
